### ISSUE TITLE
when 1.21

### ISSUE THREAD

**Issue by QiZiZhiCai** [nat212/steppy#4]
cant live without it
hope it gets updated soon
🥺

**Comment by nat212** [comment]
I'm glad you enjoy it :)
I'm looking at updating it to 1.21, and I'm going to try make it compatible with forge and fabric

**Comment by nat212** [comment]
Working on an update to 1.21 that'll work on both neoforge and fabric, just need to test that everything works

**Comment by nat212** [comment]
This is now available on modrinth :)

**Comment by QiZiZhiCai** [comment]
wbt forge🥺
i mean not neoforge🥺

**Comment by nat212** [comment]
Hi there :)
NeoForge was forked from Forge due to the lead developer of Forge being a known problem in the modding community, so a lot of mod developers (including myself) decided to move away from Forge and support NeoForge instead.
You can see more information here: https://neoforged.net/news/theproject/
I also use Architectury to allow developing for multiple modloaders, and it currently doesn't support Forge on newer versions of Minecraft.
